### ISSUE TITLE
Directory Traversal Vulnerability

### ISSUE THREAD

**Issue by JacksonGL** [caspervonb/bitty#1]
This npm package has Directory Traversal issue

This security vulnerability is similar to the issues that nsp reported here:
https://nodesecurity.io/advisories?search=directory+traversal

More details:
The bitty package creates an HTTP server that does not do enough sanity checking.
Consequently, using /../ in the url can return the content of any file on the hard drive.

For example:
http://localhost:<port number>/../../../file

**Comment by caspervonb** [comment]
Valid point but, trump card, local development tool! Also its an old one, basically from my ~/.bin folder.

Appreciate the report, likely wontfix (this is pending deletion really, made better tools since then)

**Comment by JacksonGL** [comment]
I see. Thanks for your reply. My point is that the package has 8k+ downloads on npm. Even if it is only used as a local development tool, it serves all files of the hosting machine (not just those in the working directory) to the local network, which is kind of dangerous.
